#!/usr/bin/env python3

import os
import pdb
import sys
import readline
import traceback
#from datetime import datetime
#from tzlocal import get_localzone
from tempfile import NamedTemporaryFile

from source import lib
from source import log
from source.parser import DB, MessageParserThread, Message
from source.commands import *

try:
    path = sys.argv[1]
except:
    log.err('Usage: %s <path>' % sys.argv[0])
    sys.exit(1)

"""
tab completion
"""
commands = ('start', 'start reset', 'end', 'end reset', 'export', 'colorexport',
            'list events', 'list source', 'list category', 'list attributes',
            'suspicious ip', 'suspicious user', 'plot')
def debug_log(*args, **kwargs):
    with open('/tmp/warlock_debug', 'a+') as f:
        print(*args, **kwargs, file=f)
def completer(text, state):
    debug_log('completing')
    debug_log('  text:', text)
    debug_log('  state:', state)
    try:
        # commands
        prepend = ''
        options = [i for i in commands if i.startswith(text)]
        debug_log('    found %d command options' % len(options))
        # filters
        if not options:
            debug_log('  ... no options, this is a filter')
            prepend = ' '.join(text.split(' ')[:-1]) + ' '
            debug_log('    prepend: "%s"' % prepend)
            last_word = text.split(' ')[-1]
            debug_log('    last word: "%s"' % last_word)
            # TODO get valid values for given filter
            options = [i for i in 
                       (list(Filter.operators.keys()) +
                        list(Filter.queries.keys()) +
                        list(set(x for e in events for x in e.attributes.keys())))
                       if text.startswith(commands) and i.startswith(last_word)]
            debug_log('    found %d filter options' % len(options))
        return prepend + options[state] + ' '
    except IndexError:
        return None
    except:
        traceback.print_exc()

readline.parse_and_bind('tab: complete')
readline.set_completer(completer)

def match_hook(substitution, matches, longest_len):
    # TODO show command or only last atomic valid filter
    # TODO print help for commands?
    for match in matches:
        print('>' + match)
    print(self.prompt.rstrip(), readline.get_line_buffer(), sep='', end='')
    sys.stdout.flush()
readline.set_completer_delims('')
#readline.set_completion_display_matches_hook(match_hook)

"""
load data
"""
logs = {}

if os.path.isfile(path):
    #log.info('Dealing with file.')
    try:
        with open(path, 'r') as f:
            logs[path] = f.read().splitlines()
    except UnicodeDecodeError:
        log.err('%s is binary.' % path)

elif os.path.isdir(path):
    #log.info('Dealing with path.')
    for root, ds, fs in os.walk(path):
        for f in fs:
            filepath = os.path.join(root, f)
            try:
                with open(filepath, 'r') as f:
                    logs[filepath] = f.read().splitlines()
            except UnicodeDecodeError:
                log.err('%s is binary.' % filepath)

"""
parse events
"""

events = []
for filename, lines in logs.items():
    file_events = []
    log.info(filename)
    # skip /var/log/messages (non-critical stuff there)
    #      /var/log/debug.log (non-critical stuff there)
    if any([
        re.search(r'messages(\.\d)?$', filename),
        re.search(r'debug(\.log)?(\.\d)?$', filename),
        re.search(r'setuid\.(changes|today|yesterday)$', filename),
        re.search(r'installer/syslog$', filename),
    ]):
        continue
    #thread_count = 4 if len(lines) > 1000 else 1 # slower...
    thread_count = 1
    thread_line_count = len(lines) // thread_count + 1
    threads = [MessageParserThread(filename, chunk) 
               for chunk in lib.chunks(lines, thread_line_count)] 
    for t in threads:
        t.start()
    for t in threads:
        t.join()
        # add data
        file_events += t.results
        #file_events += t.result

    
    # if file mtime < last event, reyear backwards
    mtime = lib.normalize_datetime(os.path.getmtime(filename))
    #log.info('  mtime:', mtime)
    try: # as timestamp might be None
        if file_events and mtime < file_events[-1].timestamp:
            if Message.debug_parsing:
                log.info('  Using mtime (%s) to fix dates.' % str(mtime))
            last_event_timestamp = mtime
            
            for event in file_events[::-1]:
                #print('fixing timestamp', event.timestamp)
                #print('fixing timestamp', event.message)
                event.timestamp = event.timestamp.replace(year=last_event_timestamp.year)
                # lower year; consider year change and time saving
                if (event.timestamp - last_event_timestamp).total_seconds() > 3600:
                    #print(' decrementing year, cause actual', event.timestamp, '> last', last_event_timestamp)
                    #print('  for', event.message)
                    event.timestamp = event.timestamp.replace(year=last_event_timestamp.year - 1)
                #print(' new timestamp:', event.timestamp)
                last_event_timestamp = event.timestamp
    except:
        log.err('  Year fix failed.')
        traceback.print_exc()
    events += file_events
        
events = sorted(events, key=lambda x: (x.timestamp 
                                       if x.timestamp 
                                       else lib.normalize_datetime()))
#'''
# write into DB
f = NamedTemporaryFile()
lib.db = DB(f.name)
#lib.db = DB('/tmp/warlock.db')
events_by_db_id = OrderedDict()
for event in events:
    if event and event.timestamp:
        entry_id = lib.db.insert_message(event)
        event.db_id = entry_id
        events_by_db_id[entry_id] = event
lib.db.commit()
#'''

#timed_events = [e for e in events['time'] 
#                if e.category != 'UNKNOWN' and e.timestamp]
#if not timed_events:
#    log.warn('No timed events loaded.')
#    lib.exit_program(None, None)

start = events[0].timestamp
end = events[-1].timestamp
log.info('Found %d events from %s to %s.' % (len(events), start, end))


events_by_db_id_limited = events_by_db_id
"""
deal with commands
"""
while True:
    # get command
    try:
        cmd = input(log.COLOR_PURPLE + '--} ' + log.COLOR_NONE).strip()
    except EOFError: # Ctrl+D -> quit
        log.newline()
        lib.exit_program(None, None)
    if len(cmd) == 0:
        continue

    # quit?
    if lib.quit_string(cmd):
        log.warn('Do you really want to quit? ', new_line=False)
        if lib.positive(input()):
            lib.exit_program(None, None)
        continue

    # test
    if cmd.startswith('test'):
        #venn(events, 'category == auth', 'severity == critical')
        list_overview(by_db_id, 'source', 'score >= 5')
        
        pass

    # set start
    elif cmd.startswith('start '):
        value = cmd[6:]
        if value == 'reset':
            given = events[0].timestamp
        else:
            given = lib.normalize_datetime(value, silent=True)
            if not given:
                display_filter = Filter.parse(value)
                matches = display_filter.run()
                given = events_by_db_id.items()[matches[0] if matches else 0][1].timestamp
        if given:
            start = given
            log.info('Working with events from %s to %s.' % (start, end))
            events_by_db_id_limited = OrderedDict([(db_id, e) for db_id, e in events_by_db_id.items() if start <= e.timestamp <= end])
        else:
            log.err('Usage: start <datetime>|reset|<filter>')

    # set end
    elif cmd.startswith('end '):
        value = cmd[4:]
        if value == 'reset':
            given = events[-1].timestamp
        else:
            given = lib.normalize_datetime(value, silent=True)
            if not given:
                display_filter = Filter.parse(value)
                matches = display_filter.run()
                given = events_by_db_id.items()[matches[-1] if matches else -1][1].timestamp
        if given:
            end = given
            log.info('Working with events from %s to %s.' % (start, end))
            events_by_db_id_limited = OrderedDict([(db_id, e) for db_id, e in events_by_db_id.items() if start <= e.timestamp <= end])
        else:
            log.err('Usage: end <datetime>|reset|<filter>')

    # list events
    elif cmd.startswith('list events'):
        """
        list detailed events based on optional display filter
        """
        log.info('Showing events from %s to %s.' % (start, end))
        list_events(events_by_db_id_limited, cmd[12:])

    # list suspicious
    elif cmd.startswith('suspicious'):
        try:
            log.info('Showing suspicious for events from %s to %s.' % (start, end))

            list_suspicious(events_by_db_id_limited, cmd.split()[1], ' '.join(cmd.split()[2:]))
        except:
            traceback.print_exc()
            log.err('Usage: suspicious ip|user [<filter>]')
    
    # list X
    elif cmd.startswith('list'):
        try:
            log.info('Showing counts for events from %s to %s.' % (start, end))
            list_overview(events_by_db_id_limited, cmd.split()[1], ' '.join(cmd.split()[2:]))

        except IndexError:
            log.err('Usage: list events|source|category|<attribute> [<filter>]')
        except:
            traceback.print_exc()
   
    # plot
    elif cmd.startswith('plot'):
        plot(events_by_db_id_limited, cmd[4:])

    # export into file
    elif cmd.startswith(('export ', 'colorexport ')):
        parts = cmd.split()

        display_filter = Filter.parse(' '.join(parts[2:]))
        matches = display_filter.run() if display_filter else events_by_db_id_limited.keys()
        colorize = ((lambda e: str(e))
                    if parts[0] == 'export' 
                    else (lambda e: '%s%s%s' % (lib.severity_colors[e.severity],
                                                str(e),
                                                log.COLOR_NONE)))
        if matches:
            try:
                with open(parts[1], 'w') as f:
                    for db_id in matches:
                        f.write(colorize(events_by_db_id_limited[db_id]))
                        f.write('\n')
            except:
                traceback.print_exc()
                log.err('Cannot export log entries!')
    else:
        log.warn('Unknown command.')

